default[:graphite][:user]             = "graphite"
default[:graphite][:whisper_data_dir] = "/data/graphite/whister"
default[:graphite][:carbon_address]   = "127.0.0.1"
default[:graphite][:server_name]      = "_"
default[:graphite][:graphite_version] = "0.9.9"
default[:graphite][:carbon_version] = "0.9.9"
default[:graphite][:whisper_version] = "0.9.9"
