default[:graphite][:user]             = "graphite"
default[:graphite][:whisper_data_dir] = "/data/graphite/whister"
default[:graphite][:carbon_address]   = "127.0.0.1"
default[:graphite][:server_name]      = "_"
default[:graphite][:nginx_interface]  = "127.0.0.1"
default[:graphite][:nginx_port]       = "80"